services:
  - type: web
    name: pdf-to-excel-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: PORT
        value: 10000
    autoDeploy: true 